name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  dropdown_button2: ^1.8.0
  csv: ^6.0.0
  path_provider: ^2.1.4  # Add the path_provider dependency here
  mapbox_gl: 0.16.0 # Replace with the latest version
  http: ^1.0.0
  shared_preferences: ^2.0.15




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/image_8.png
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/vector_126_x2.svg
  - assets/vectors/vector_107_x2.svg
  - assets/vectors/polygon_26_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/vector_136_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/vector_78_x2.svg
  - assets/vectors/rectangle_302_x2.svg
  - assets/vectors/polygon_11_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_135_x2.svg
  - assets/vectors/vector_140_x2.svg
  - assets/images/image_8.png
  - assets/vectors/rectangle_303_x2.svg
  - assets/vectors/polygon_17_x2.svg
  - assets/vectors/rectangle_296_x2.svg
  - assets/vectors/polygon_110_x2.svg
  - assets/vectors/vector_129_x2.svg
  - assets/images/image_9.png
  - assets/images/image_8.png
  - assets/images/download_3_fotor_bg_remover_20240725213131.png
  - assets/images/image_11.png
  - assets/vectors/polygon_3_x2.svg
  - assets/images/image_5.png
  - assets/images/image_6.png
  - assets/images/images_photoroom_fotor_bg_remover_20240726178241.png
  - assets/images/image_4.png
  - assets/images/image_7.png
  - assets/images/image_8.png
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/vector_133_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_119_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/ellipse_31_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/vector_81_x2.svg
  - assets/vectors/vector_87_x2.svg
  - assets/vectors/polygon_117_x2.svg
  - assets/vectors/vector_115_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/ellipse_12_x2.svg
  - assets/vectors/ellipse_22_x2.svg
  - assets/vectors/vector_85_x2.svg
  - assets/vectors/rectangle_3011_x2.svg
  - assets/vectors/vector_110_x2.svg
  - assets/vectors/vector_130_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/polygon_24_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/vector_106_x2.svg
  - assets/vectors/vector_104_x2.svg
  - assets/vectors/vector_97_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/images/image_8.png
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_100_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/rectangle_304_x2.svg
  - assets/vectors/vector_91_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/polygon_116_x2.svg
  - assets/vectors/polygon_22_x2.svg
  - assets/vectors/vector_92_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/vector_134_x2.svg
  - assets/vectors/vector_111_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/vector_127_x2.svg
  - assets/vectors/vector_102_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/vector_89_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/vector_116_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/vector_94_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/images/image_8.png
  - assets/images/image_1.png
  - assets/images/image_6.png
  - assets/images/image_5.png
  - assets/images/images_photoroom_fotor_bg_remover_20240726178241.png
  - assets/images/image_4.png
  - assets/images/rectangle_8.png
  - assets/images/images_photoroom_fotor_bg_remover_20240726178241.png
  - assets/vectors/vector_13_x2.svg
  - assets/images/image_8.png
  - assets/vectors/polygon_14_x2.svg
  - assets/vectors/vector_120_x2.svg
  - assets/vectors/rectangle_29_x2.svg
  - assets/vectors/polygon_118_x2.svg
  - assets/vectors/vector_131_x2.svg
  - assets/vectors/rectangle_308_x2.svg
  - assets/images/image_8.png
  - assets/vectors/rectangle_301_x2.svg
  - assets/vectors/rectangle_293_x2.svg
  - assets/vectors/vector_142_x2.svg
  - assets/vectors/vector_82_x2.svg
  - assets/vectors/polygon_19_x2.svg
  - assets/vectors/polygon_12_x2.svg
  - assets/images/image_8.png
  - assets/images/images_photoroom_fotor_bg_remover_20240726178241.png
  - assets/images/image_4.png
  - assets/images/image_8.png
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/vector_123_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/vectors/ellipse_32_x2.svg
  - assets/vectors/polygon_18_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/ellipse_11_x2.svg
  - assets/vectors/vector_108_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/polygon_25_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_118_x2.svg
  - assets/vectors/vector_84_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/vector_83_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_105_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/rectangle_3010_x2.svg
  - assets/vectors/vector_101_x2.svg
  - assets/vectors/ellipse_2_x2.svg
  - assets/images/image_8.png
  - assets/images/image_18.png
  - assets/images/image_8.png
  - assets/vectors/polygon_23_x2.svg
  - assets/vectors/rectangle_30_x2.svg
  - assets/vectors/vector_96_x2.svg
  - assets/vectors/polygon_119_x2.svg
  - assets/vectors/rectangle_297_x2.svg
  - assets/images/image_8.png
  - assets/vectors/rectangle_294_x2.svg
  - assets/vectors/polygon_13_x2.svg
  - assets/vectors/vector_99_x2.svg
  - assets/vectors/polygon_16_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/rectangle_306_x2.svg
  - assets/images/image_8.png
  - assets/images/image_17.png
  - assets/images/image_9.png
  - assets/images/green_thumbs_up_1124611.png
  - assets/images/image_8.png
  - assets/vectors/polygon_31_x2.svg
  - assets/images/image_8.png
  - assets/vectors/vector_125_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/polygon_21_x2.svg
  - assets/vectors/vector_113_x2.svg
  - assets/vectors/vector_80_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/vector_95_x2.svg
  - assets/vectors/vector_122_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/vector_93_x2.svg
  - assets/vectors/polygon_114_x2.svg
  - assets/vectors/vector_132_x2.svg
  - assets/vectors/ellipse_1_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/ellipse_21_x2.svg
  - assets/vectors/vector_114_x2.svg
  - assets/vectors/vector_143_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_117_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/ellipse_3_x2.svg
  - assets/vectors/rectangle_309_x2.svg
  - assets/vectors/vector_90_x2.svg
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/images/image_8.png
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/polygon_2_x2.svg
  - assets/vectors/vector_79_x2.svg
  - assets/vectors/polygon_112_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_112_x2.svg
  - assets/vectors/vector_103_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/vector_128_x2.svg
  - assets/vectors/vector_137_x2.svg
  - assets/vectors/vector_139_x2.svg
  - assets/vectors/rectangle_3012_x2.svg
  - assets/images/image_8.png
  - assets/vectors/rectangle_291_x2.svg
  - assets/vectors/polygon_113_x2.svg
  - assets/vectors/polygon_15_x2.svg
  - assets/vectors/vector_77_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/rectangle_305_x2.svg
  - assets/images/image_8.png
  - assets/vectors/rectangle_295_x2.svg
  - assets/vectors/polygon_1_x2.svg
  - assets/vectors/rectangle_307_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/polygon_111_x2.svg
  - assets/images/image_8.png
  - assets/vectors/vector_141_x2.svg
  - assets/vectors/vector_124_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/rectangle_292_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_98_x2.svg
  - assets/vectors/vector_86_x2.svg
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/polygon_27_x2.svg
  - assets/vectors/vector_138_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_109_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_121_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/vector_88_x2.svg
  - assets/vectors/polygon_115_x2.svg
  - assets/vectors/vector_75_x2.svg
  - assets/images/image_16.png
  - assets/images/images_4_fotor_bg_remover_202407261627541.png
  - assets/images/image_3.png
